name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Login to Docker Hub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build node-app
      - name: Docker push
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml push node-app
      - name: Copy config via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSPHRASE }}
          source: "${{ github.workspace }}/docker-compose.yml", "${{ github.workspace }}/docker-compose.prod.yml"
          target: ${{ secrets.PROJECT_PATH }}
          strip_components: 2
          overwrite: true
      - name: Run docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull node-app
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --no-deps node-app

