name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" docker login -u r2d1 
      - name: Docker build
        run: docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
      - name: Docker push
        run: |
          docker image ls
          docker push r2d1/node-app:latest

